### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getElementById' of null

### ISSUE THREAD

**Issue by gui-wf** [allefeld/atom-pdfjs-viewer#7] opened 2020-12-05 02:03 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: "Manjaro Linux"
**Thrown From**: [pdfjs-viewer](https://github.com/allefeld/atom-pdfjs-viewer) package 1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getElementById' of null

```
At /home/theodorediketer/.atom/packages/pdfjs-viewer/lib/pdfjs-viewer-view.js:81

TypeError: Cannot read property 'getElementById' of null
    at PdfjsViewerView.injectStyle (/packages/pdfjs-viewer/lib/pdfjs-viewer-view.js:81:34)
    at PdfjsViewerView.viewerLoaded (/packages/pdfjs-viewer/lib/pdfjs-viewer-view.js:48:10)
    at /packages/pdfjs-viewer/lib/pdfjs-viewer-view.js:34:54)
```

### Commands

```
     -2:36.9.0 snippets:expand (input.hidden-input)
     -2:36.9.0 editor:indent (input.hidden-input)
     -2:36.5.0 intentions:highlight (input.hidden-input)
     -2:36.4.0 autocomplete-plus:activate (input.hidden-input)
     -2:35.2.0 autocomplete-plus:confirm (input.hidden-input)
     -2:34.3.0 core:backspace (input.hidden-input)
     -2:33 intentions:highlight (input.hidden-input)
     -2:32.9.0 core:save (input.hidden-input)
     -2:06.2.0 core:close (iframe.pdfjs-viewer)
  2x -1:03.3.0 core:backspace (input.hidden-input)
     -0:54.1.0 intentions:highlight (input.hidden-input)
     -0:54 core:select-all (input.hidden-input)
     -0:49.9.0 core:backspace (input.hidden-input)
     -0:43.4.0 intentions:highlight (input.hidden-input)
     -0:43.3.0 core:select-all (input.hidden-input)
  4x -0:41.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
atom-material-darker-syntax 1.1.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
autocomplete-clang 0.13.1 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
clang-format 2.0.8 
deep-purple-syntax 0.2.18 
file-icons 2.1.44 
formatter 2.12.4 
formatter-clang-format 0.1.2 
highlight-selected 0.17.0 
intentions 1.1.5 
kite 0.197.0 
language-mips 0.3.0 
linter 3.1.1 
linter-clang 4.1.2 
linter-rust 1.0.1 
linter-ui-default 2.1.5 
minimap 4.35.6 
minimap-highlight-selected 4.6.2 
minimap-linter 2.2.2 
moonlight 0.11.0 
pdfjs-viewer 1.0.0 
purple-rain 0.4.8 
python-linters 0.0.5 
teletype 0.13.4 
threejs-snippets 0.0.8 
```

**Comment by allefeld** [comment] 2020-12-07 19:54
Thanks for the report. Unfortunately, it's hard for me to tell what's going on, because I don't know the context. When does the error occur? What are the steps to reproduce it?

I'm using the same version on Debian 10, and don't see an error when opening PDFs.

**Comment by gui-wf** [comment] 2020-12-07 21:44
It was a really weird bug cause it only happened right after I installed
kite through Atom. After a restart I was able to use atom-pdfjs-viewer
normally.

**Comment by allefeld** [comment] 2020-12-07 21:56
Thanks! I'm closing this because you say the bug doesn't occur anymore, but feel free to reopen if it happens again.

**Closed as completed by allefeld** 2020-12-07 21:56 UTC
